### ISSUE TITLE
Peppymeter analog input or i2s input from Raspberry

### ISSUE THREAD

**Issue by marcocand** [project-owner/PeppyMeter#1]
Hi,

I'm quite new with Raspbian but experienced with UNIX system since 1983. I've installed peppymeter and peppyalsa. I'm willing to use peppymeter with fe-pi-audio-z-v2 audio board but
I do not know how to make fe-pi-audio-z-v2 writing to the  peppymeter pipe.
Any suggestions?

Many thanks in advance!

**Comment by project-owner** [comment]
Hello,

You need to configure your software player to use peppyalsa device.
For example to use 'aplay' program which is available in all Raspbian images:
aplay -D peppyalsa YOUR_FILE.wav
All Linux software audio players should have ability to specify output device.
The ALSA configuration file was described here:
https://github.com/project-owner/peppyalsa.doc/wiki/Configuration
Your audio board should be defined in that file like this:
slave.pcm "hw:0,0"
You need to check that it's really using device 0 and subdevice 0 using command:
aplay -l
If it's using different device you need to change the configuration file.

Good luck!

**Comment by marcocand** [comment]
Hi,
many thanks for your hints about software player and peppymeter.
If I want to use the audio device input for peppymeter instead of
software player how can I proceede?
Bye!

**Comment by project-owner** [comment]
Hi,

I have never used PeppyMeter with any audio input boards only with output.
The input for peppyalsa plugin is PCM signal. So you need to create a device
in ALSA configuration file which can provide such signal and redirect it to the
peppyalsa plugin.

Regards

**Comment by marcocand** [comment]
Hi,

I had another project to follow so I've placed the project on pause mode.
Now I'm back, many thanks for your answer. I do not know how to create  a device
in ALSA configuration, do you have any suggestions? Any effort estimation to do this
device from your side?

Many thanks!

**Comment by project-owner** [comment]
Hi,

Which OS do you use? What's the output of the following command when the board is connected to the Pi Zero?
aplay -l

Best regards

**Comment by marcocand** [comment]
Hi,

I'm currently using a PI 3c.

The Op sys version is; 
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

the results of aplay -l is
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

Bye!

**Comment by project-owner** [comment]
I believe your audio board in aplay output is this one:
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]

If this is the case you need to specify
`hw:1,0`
in file .asoundrc described here:
[https://github.com/project-owner/peppyalsa.doc/wiki/Configuration](url)

Then try to run WAV audio file like this:
`aplay -D peppyalsa YOUR_FILE.wav`
If you have OS with desktop then you should see the signal in PeppyMeter GUI. You can also see the signal in terminal (e.g. SSH session through Putty) if you run the testing program described here:
[https://github.com/project-owner/peppyalsa.doc/wiki/VU-Meter-Usage#using-client-program-supplied-with-plugin](url)

Best regards

**Comment by marcocand** [comment]
Hi,

many thanks for your answer, but I think I've not been clear with my request.
I do not want to play a wave file with peppy meter, I would like the peppy meter input to be
the usb audio dongle input.

Many thanks!

**Comment by project-owner** [comment]
Hi,

So you want to show the level for microphone or Line  In, right? As I mentioned already I've never tried to use PeppyMeter for input devices. Those devices should be also available as ALSA devices. You need to find out the device's card/device/subdevice and use this info the same way as I explained in my previous post. For example your Line In on card 1 can be device or subdevice 0 and Line Out device or subdevice 1.

Best regards

**Comment by marcocand** [comment]
Hi,
sorry for the delay but I've been busy.

I'm able to read from USB audio device input and out to device out.

I've found two possible way to output the USB audio device input to peppy meter they are;

arecord -D hw:1,0 -d 5000 -f dat -c 1 | aplay -D peppyalsa -  &

arecord  -D hw:1,0 -d 5000 -f cd test.wav -c 1 | aplay -D peppyalsa test.wav &

Both of them gives me channel error…

Any suggestion?

Many thanks in advance!

**Comment by project-owner** [comment]
Hi, 

Did you try the same approach without peppyalsa? Does it work?

Best regards

**Comment by marcocand** [comment]
Hi,

I've completely reinstalled raspbian, peppymeter and peppy alsa.

I have now the microphone USB input to the loudspeaker USB output using the command
                     arecord -D hw:1,0 -d 5000 -f dat -c 1 | aplay -

Also the PeppyMeter is working with the USB input using the command
                    arecord -D hw:1,0 -d 5000 -f dat -c 1 | aplay -D peppyalsa - 

Unfortunatelly there is a sort of 0,3 second of delay between the audio in and peppymeter index.

Any possible way to read from aplay the USB input without such a delay?

Many thanks in advance!!

**Comment by project-owner** [comment]
Hi,

Do you see the delay with GUI or without (https://raw.githubusercontent.com/project-owner/peppyalsa.doc/master/images/show.png)? Probably it could be improved by adjusting ALSA buffer size. Though I've never done that.  Another thing could be to try to assign the player higher priority using 'nice' utility. Please let me know if you will find a way to reduce the delay.

Best regards

**Comment by marcocand** [comment]
Hi,
I've done some other tests, using 
arecord -D hw:1,0 -d 5000 -f dat -c 1 | aplay -
I've seen there is still the 0,3 second delay to the audio output, so I think the delay it is
due to the arecord conversion time.

We do not see the delay using the
aplay -D peppyalsa /usr/share/sounds/alsa/Side_Left.wav
because of the aplay is faster converting the is faster reading the .wav and the audio out
delay is the same as the peppymeter.

I've tried to use nice and tried to reduce arecord sampling rate but same delay.

Any other ideas to improve aplay conversion time?

Many thanks in advance!

Bye!

**Comment by marcocand** [comment]
Sorry I did confusion with cut and paste..

We do not see the delay using the
aplay -D peppyalsa /usr/share/sounds/alsa/Side_Left.wav
because of the aplay is faster  reading the .wav and the audio out
delay is the same as the peppymeter.

Bye!

**Comment by project-owner** [comment]
Hi,

Do you mean that without peppyalsa plugin there is the same delay? In this case as you mentioned it's 'arecord' which adds that delay. I'm not sure how to improve that part (arecord). 

Best regards

**Comment by marcocand** [comment]
Hi,

found a solution, we cannot improve the arecod but we can delay audio input as follows;

mkfifo stream1.wav
mkfifo stream2.wav
aplay -D peppyalsa stream2.wav
aplay stream1.wav 
arecord -D hw:1,0 -d 5000 -f dat -c 1 | tee stream1.wav | tee stream2.wav 

It works the arecord delay it is applied to both fifo  so the meter delay it is the same
as audio aut.

Many thanks for your help!

Bye!

**Comment by project-owner** [comment]
Great! I'm glad that you found the solution. I have the user Gallery for the Peppy Player:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Gallery

Maybe it's time to create the same for PeppyMeter ;) Please let me know if you will decide to share your project.

Thank you!
Best regards

**Comment by marcocand** [comment]
Hi,

unfortunately I've checked the USB audio out quality and it is very bad…
I'm preparing an High Fidelities Mos Audio power amplifier I cannot use the USB audio out.
So the work arounf I've found it is not solving the problem.

I'm thinking to use an analog to i2s external codec, do you think it is possible from
peppy meter to read the Raspberry i2s input instead of reading the peppyalsa fifo?

Many thanks!

Bye!

**Comment by project-owner** [comment]
Hi,

I don't understand what is your audio source? What are you trying to play -
audio files, CDs or what? There are several DAC and Amplifier boards on the
market for Raspberry Pi.

PeppyMeter cannot read i2s signal.

Best regards

**Comment by marcocand** [comment]
Hi,

I would like to build an HIFI power amplifier, all the audio chain mast be analog to keep audio hight
fidelity. All the power amplifier volume, tone and input selection should be controlled by raspberry.
Also the Vmeter should be managed by raspberry.
The audio input are not raspberry wave file but real analog input.
If the Peppy Meter is delayed from the audio in I should find a different solution.

I'm wondering if you could modify PeppyMeter to read i2s or digital in instead of using
Peppyalsa and fifo.

Bye!

**Comment by project-owner** [comment]
Hi,

As far as I understand you don't use Pi in the main audio chain and need it
only for secondary functionality. In this case I think Pi doesn't need high
quality signal and could work fine with that USB input. Maybe I don't
understand what you are planning.

The main audio system on Linux is ALSA. All audio devices should provide
ALSA drivers. Using ALSA plugin chain PeppyMeter can handle any device.
Writing I2S driver for PeppyMeter is very low level and pretty complicated
task. I'm not sure the effort will worth the benefits.

Best regards
