### ISSUE TITLE
Signal level problem

### ISSUE THREAD

**Issue by Ravens62** [project-owner/PeppyMeter#10]
After installing the Official 7 ".img and checking the display functionality, I connect Hifiberry AMP2.
Edited in Boot/Config.txt, Webui set to player, linear, digital, 20 %.
Then it happens that the signal level is so low that the indicators do not move ...

The indicators are visibly moving when the volume increases.
And when I use the spectrum analyzer, there is a visible movement even at 20%.
I don't know where to adjust.

.asoundrc
pcm.!default {
  type plug
  slave.pcm myequal;
}
ctl.!default {
  type hw card 0
}
pcm.myequal {
  type equal;
  slave.pcm reformat;
}
pcm.reformat {
  type lfloat
  slave {
    pcm "mypeppy"
    format S16_LE
  }
}
pcm.mypeppy {
  type meter
  slave.pcm "plughw:0,0"
  scopes.0 peppyalsa
}
ctl.equal {
  type equal;
}
pcm_scope.peppyalsa {
  type peppyalsa
  decay_ms 400
  meter "/home/pi/myfifo"
  meter_max 100
  meter_show 0
  spectrum "/home/pi/myfifosa"
  spectrum_max 100
  spectrum_size 30
}
pcm_scope_type.peppyalsa {
  lib /usr/local/lib/libpeppyalsa.so
}

**Comment by t0bit0bsen** [comment]
Hi Ravens62,

try to set the volume control to hardware in the webui. The Hifiberry Amp supports that.  This solved the issue for me. 

Regards

Tobias

**Comment by Ravens62** [comment]
Hi t0bit0bsen,
It doesn't work for me.
It is not possible to control the volume via the display.

**Comment by t0bit0bsen** [comment]
I will check my settings the next days. Is the Hifiberry Amp hw card 0? You can check that with aplay -l and aplay -L. If not, backup your .asoundrc and change the settings correct hw card or disable the other sound cards.

**Comment by t0bit0bsen** [comment]
I could reach my settings by phone, here is my .asoundrc and the output of aplay -l

pi@raspberrypi:~ $ cat .asoundrc
pcm.!default {
  type plug
  slave.pcm myequal;
}
ctl.!default {
  type hw card 2
}
pcm.myequal {
  type equal;
  slave.pcm reformat;
}
pcm.reformat {
  type lfloat
  slave {
    pcm "mypeppy"
    format S16_LE
  }
}
pcm.mypeppy {
  type meter
  slave.pcm "plughw:2,0"
  scopes.0 peppyalsa
}
ctl.equal {
  type equal;
}
pcm_scope.peppyalsa {
  type peppyalsa
  decay_ms 400
  meter "/home/pi/myfifo"
  meter_max 100
  meter_show 0
  spectrum "/home/pi/myfifosa"
  spectrum_max 65535
  spectrum_size 17
  logarithmic_frequency = 1
  logarithmic_amplitude = 1
  smoothing_factor = 20
  window=3
}

pcm_scope_type.peppyalsa {
  lib /usr/local/lib/libpeppyalsa.so
}



pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 2: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 [HiFiBerry DAC+ HiFi pcm512x-hifi-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $

**Comment by Ravens62** [comment]
Peppy plays everything, radio, NAS music, works as it should, just has a weak signal.

aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 [HiFiBerry DAC+ HiFi pcm512x-hifi-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

**Comment by t0bit0bsen** [comment]
Sorry, I was wrong. You have to set it to amixer. Hardware would be some external amplifier. And I have Digital with a capital D in my settings. If I slide the volume on the display I can see the slider in amixer via ssh moving.

**Comment by Ravens62** [comment]
Yeah, this works.
I had another display, 3.5 "GPIO, and there it had to be on the player. Now I have 4.3" DSI, and I did not change the settings.
Thanks for the help.

**Comment by Ravens62** [comment]
Yeah, this works.
I had another display, 3.5 "GPIO, and there it had to be on the player. Now I have 4.3" DSI, and I did not change the settings.
Thanks for the help.
