### ISSUE TITLE
Animation on display does not work

### ISSUE THREAD

**Issue by adolfotregosa** [project-owner/PeppyMeter#11]
Hi. I have a strange issue with the last available version. My I2C meters work fine but the display animation does not, I mean it starts up but nothing happens on screen. I have a old Peppymeter folder backup and that works fine. 

I have no idea where to start. How can I help ?

**Comment by project-owner** [comment]
Hi,

I've added the checking for empty value:
https://github.com/project-owner/PeppyMeter/blob/75f550a2c1e41d46ab261e972d956649827a089e/i2cinterface.py#L105
Please try the latest code with that fix.

Best regards

**Comment by adolfotregosa** [comment]
> Hi,
> 
> I've added the checking for empty value:
> 
> https://github.com/project-owner/PeppyMeter/blob/75f550a2c1e41d46ab261e972d956649827a089e/i2cinterface.py#L105
> 
> 
> Please try the latest code with that fix.
> Best regards

You got it the wrong way ! I2C works fine, the display does not ! See the video bellow. 

[https://youtu.be/RibWopfU0TE](url)

old version:

[https://youtu.be/gQFYD-i7L5c](url)

**Comment by project-owner** [comment]
OK, please use the fixed code anyway.
Could you disable I2C in the config.txt file and see if display will work?

Thank you!

**Comment by adolfotregosa** [comment]
> OK, please use the fixed code anyway. Could you disable I2C in the config.txt file and see if display will work?
> 
> Thank you!

It does not work.

**Comment by project-owner** [comment]
I believe you have display enabled in the config file:
output.display = True
Could you also enable logging:
https://github.com/project-owner/PeppyMeter/blob/75f550a2c1e41d46ab261e972d956649827a089e/config.txt#L14
and see if there are any errors in the log?

Thank you!

**Comment by adolfotregosa** [comment]
> I believe you have display enabled in the config file: output.display = True Could you also enable logging:
> 
> https://github.com/project-owner/PeppyMeter/blob/75f550a2c1e41d46ab261e972d956649827a089e/config.txt#L14
> 
> 
> and see if there are any errors in the log?
> Thank you!

as far I can tell, everything is working correctly but I have no animation onscreen.

[config.txt](https://github.com/project-owner/PeppyMeter/files/11072788/config.txt)
![image](https://user-images.githubusercontent.com/7437931/227799335-7c6196de-b05e-45c8-abf8-4a94567ffed4.png)

working peppymeter log output with logging enabled:

![image](https://user-images.githubusercontent.com/7437931/227799427-3b9a6277-a072-4d46-a4f5-f4d8d334d2b4.png)

**Comment by project-owner** [comment]
Hmm, no errors. I'll try to setup I2C on my side. It will take some time. Meanwhile could you add additional logging?
Add
```
import logging
```
 to this line: https://github.com/project-owner/PeppyMeter/blob/75f550a2c1e41d46ab261e972d956649827a089e/linear.py#L19
add:
```
logging.debug(d)
```
to this line:
https://github.com/project-owner/PeppyMeter/blob/75f550a2c1e41d46ab261e972d956649827a089e/linear.py#L55
align it with previous line using spaces not tabs.
Restart and see if it will print data to the log.

Thank you!

**Comment by adolfotregosa** [comment]
> Hmm, no errors. I'll try to setup I2C on my side. It will take some time. Meanwhile could you add additional logging? Add
> 
> ```
> import logging
> ```
> 
> to this line:
> 
> https://github.com/project-owner/PeppyMeter/blob/75f550a2c1e41d46ab261e972d956649827a089e/linear.py#L19
> 
> 
> add:
> ```
> logging.debug(d)
> ```
> 
> to this line:
> 
> https://github.com/project-owner/PeppyMeter/blob/75f550a2c1e41d46ab261e972d956649827a089e/linear.py#L55
> 
> 
> align it with previous line using spaces not tabs.
> Restart and see if it will print data to the log.
> Thank you!

Forget I2C...

this is what I get, nothing I guess

![image](https://user-images.githubusercontent.com/7437931/227803919-8009ab4f-5037-46f2-b588-b5dbd0686c7c.png)

**Comment by adolfotregosa** [comment]
I dunno if this will help but you have attached the working peppymeter [PeppyMeter.zip](https://github.com/project-owner/PeppyMeter/files/11073052/PeppyMeter.zip)

**Comment by adolfotregosa** [comment]
I dunno if this will help but this is the working [PeppyMeter.zip](https://github.com/project-owner/PeppyMeter/files/11073057/PeppyMeter.zip)

**Comment by project-owner** [comment]
I hope the issue was fixed. Please try the latest code.

Thank you!

**Comment by adolfotregosa** [comment]
> I hope the issue was fixed. Please try the latest code.
> 
> Thank you!

It is !! Working perfectly. Thank you so much, really!
