### ISSUE TITLE
Left Channel Needles Caches on New Circular Meters

### ISSUE THREAD

**Issue by malanmurphy** [project-owner/PeppyMeter#12]
Although it doesn't seem to happen every time, often new circular meters load with (what I would call) a cached left needle at zero. Once the same meter drops back down zero on the left channel it will overwrite the cached needle and it goes away. Then the next meter will load and the process will repeat. Here are a few images with the needle cached and again after the meter has hit zero and reset. In the 2nd pic you can see where it was half-way reset but still lingering a bit. 

https://imgur.com/a/PCHoAch

I've tested it on two displays, 3.5" TFT and an HDMI screen, and it's the same somewhat random behavior. I've also tested setting `use.cache = False` but not sure what that actually does, same result. 

Is there setting that would affect this? Thanks!

**Comment by project-owner** [comment]
Are you using the latest PeppyMeter code?

Best regards

**Comment by malanmurphy** [comment]
Yes, the version you rev'd over the weekend. But I've seen this issue in the past on the 3.5" TFT as well.

**Comment by project-owner** [comment]
I cannot reproduce the issue when I use the default meters.
Do you use PeppyMeter as a stand-alone application or as a Volumio plugin?
Do you see the issue when you use the meters which come with PeppyMeter in resolution 1280x400?
Can you share the meter images which you use?

Best regards

**Comment by malanmurphy** [comment]
Sorry for the delay. I was able to reproduce it with the native `wide` PeppyMeters: 

https://imgur.com/a/t22CyNW

I'm running it standalone. To repo here I just used the stock `wide` images on random. In my normal deployment I'm running the Gelo5 meters (I'm not using any that have embedded artwork since I'm running Peppy standalone): 

https://community.volumio.org/t/peppymeter-templates-width-1280/59939

And the specific list I cycle through: 

meter = Gelo5_Yamaha MX2000, Gelo5_Sony TA-N77, Gelo5_BlackBlur, Gelo5_Advence, Gelo5_Technics_Black, Gelo5_Accuphase, Gelo5_Adv_X220, Gelo5_OnkyoM508

**Comment by project-owner** [comment]
Could you change the data source type, polling interval and see if you can reproduce the issue?
In the PeppyMeter configuration file config.txt change the data source type from 'pipe' to 'triangle' (or noise, saw)
```
[data.source]
type = triangle
polling.interval = 0.1
```

**Comment by malanmurphy** [comment]
I was able to recreate it with those settings (triangle), and the cached needle appears wherever the needle starts when changing meters. In this image the meter changed when the needle was just to the right of 0.001 and headed right, so the cached needle was right where the meter changed (if that makes sense). 

https://imgur.com/a/oTNih2p

**Comment by project-owner** [comment]
Please use the latest version and reopen the issue if it still exists.
