### ISSUE TITLE
Http output

### ISSUE THREAD

**Issue by balbuze** [project-owner/PeppyMeter#13]
I can't get http output to work. Tornado is not running, but no error message
my config
```
[current]
meter = random
random.meter.interval = 20
meter.size = medium
screen.width = 640
screen.height = 480
screen.size = large
output.display = True
output.serial = False
output.i2c = False
output.pwm = False
use.logging = False
frame.rate = 30
exit.on.touch = False
stop.display.on.touch = False
output.http = True
use.cache = True

[sdl.env]
framebuffer.device = /dev/fb0
mouse.device = /dev/input/event0
mouse.driver = TSLIB
mouse.enabled = True
video.driver = dummy
video.display = :0
double.buffer = False
no.frame = False

[serial.interface]
device.name = /dev/serial0
baud.rate = 9600
include.time = True
update.period = 0.1

[i2c.interface]
port = 1
left.channel.address = 0x20
right.channel.address = 0x21
output.size = 10
update.period = 0.1

[pwm.interface]
frequency = 500
gpio.pin.left = 24
gpio.pin.right = 25
update.period = 0.1

[http.interface]
target.url = http://localhost:8005/vumeter
update.period = 0.033

[web.server]
http.port = 8006

[data.source]
type = pipe
polling.interval = 0.033
pipe.name = /tmp/myfifopeppy
volume.constant = 80.0
volume.min = 0.0
volume.max = 100.0
volume.max.in.pipe = 100.0
step = 6
mono.algorithm = average
stereo.algorithm = new
smooth.buffer.size = 8
```
what's wrong?
Thanks

**Comment by project-owner** [comment]
Hi,

For HTTP you need signal source and target. PeppyMeter can work as a source and target assuming that for a target you installed a web server (e.g. Tornado).
To configure source you need to specify the following parameters in the config.txt:
```
output.display = False
output.http = True
```
The first parameter means that you don't want to show PeppyMeter UI in the source.

When you start this source PeppyMeter without target running you should see the following log messages when logging is enabled (use.logging = True):
```
...
[2023-08-20 09:37:37,695] {connectionpool.py:232} DEBUG - Starting new HTTP connection (1): localhost:8001
[2023-08-20 09:37:41,846] {connectionpool.py:232} DEBUG - Starting new HTTP connection (1): localhost:8001
[2023-08-20 09:37:45,955] {connectionpool.py:232} DEBUG - Starting new HTTP connection (1): localhost:8001
...
```
These messages show that PeppyMeter cannot connect to a web server localhost:8001
To start that web server (assuming it was installed) you can make the following changes in the target PeppyMeter config.txt:
```
output.display = True
http.port = 8001
[data.source]
type = http
```
The property output.display shows that you will use PeppyMeter UI on target side (it was disabled on the source side).
The port can be any other number. Just make sure that it's the same in the properties target.url on a source and http.port on a target.
The data source type should be 'http' for target PeppyMeter as it will receive data through HTTP.

After making all these changes start a target PeppyMeter with target configuration and then start a source PeppyMeter with source configuration and it should work.

Best regards

**Comment by balbuze** [comment]
Hello
Thank you for your explanations.
My mistake is that I thought I could send data from a source and retrieve it in my own application to display something on a remote screen using that data or on the same device.
But that's not how it's designed... What is the solution?
Thanks a lot.

**Comment by project-owner** [comment]
You can receive volume data in your application as well. It's just easier to use PeppyMeter with Tornado as a target. But you can use any other application as a target. It just should be able to receive/handle HTTP requests. It can be either Apache or any other web server like Flask or Django for Python. You can even use default 'http' server which comes with Python distribution.

**Comment by project-owner** [comment]
Please reopen if you have any issue

**Comment by balbuze** [comment]
thanks!
