### ISSUE TITLE
How to run peppymeter standalone wothout Volumio

### ISSUE THREAD

**Issue by nicolocarcagni** [project-owner/PeppyMeter#14]
Hi, simply the title. I want to use peppymeter on a raspberry pi and a hdmi display without using it as a volumio plugin. standalone. Is it possible?

**Comment by project-owner** [comment]
Sure, you can either install and configure it manually:
https://github.com/project-owner/PeppyMeter.doc/wiki/Installation
https://github.com/project-owner/PeppyMeter.doc/wiki/Configuration
or use disk image:
https://github.com/project-owner/PeppyMeter/releases

**Comment by nicolocarcagni** [comment]
Thanks
