### ISSUE TITLE
Pipewire compatibility

### ISSUE THREAD

**Issue by spagoc** [project-owner/PeppyMeter#15]
I am asking if PeppyMeter could work with Pipewire. If so a Linux desktop user, using helvum or qpgraph, could connect PeppyMeter to any audio app is running e.g. a web browser playing a youtube video.

**Comment by project-owner** [comment]
I've never tried that. If Pipewire leverages ALSA behind the scenes then it should theoretically handle PeppyMeter as well. But that should be tested.

**Comment by spagoc** [comment]
In order to achieve preliminary Pipewire compatibility and targeting  Linux desktop users I did this  effort to get feed-backs: 
[https://github.com/spagoc/PeppyMeter-4-Linux-desktop] (https://github.com/spagoc/PeppyMeter-4-Linux-desktop)
The calibration needs improvements.
Please give feed-backs.

PS Thanks for PeppyMeter and its wonderful documentation.

**Comment by project-owner** [comment]
Looks good. It looks like you don't use a peppyalsa plugin. Is it because you cannot do that with Pipewire? So you just handle PCM stream in your C program and send amplitude values to the pipe. Does it mean that you cannot handle audio files this way?

**Comment by spagoc** [comment]
Sorry for my am late answer. Yes to your questions, you are right.
