### ISSUE TITLE
Circular meter needles isn't transparent on Volumio2 image

### ISSUE THREAD

**Issue by ocean1598** [project-owner/PeppyMeter#3]
Dear PeppyMeter:

With some fiddlings, I am able to get some medium meters showing on the 7-inch (1024x600) based on Volumio2 image using 'directfb' framebuffer. The device LCD is on DSI interface with '/dev/fb0' device.

However, the needle drawing has the rectangular black box. I wonder if you have any suggestions? (Note I am not familiar with pygame or SDL library. )

<img width="895" alt="Screen Shot 2020-12-21 at 3 31 01 PM" src="https://user-images.githubusercontent.com/449259/102831864-a4e1f700-43a1-11eb-9eca-75ca33841e5b.png">

**Comment by project-owner** [comment]
Hi,

I've never tried to use the 'directfb' video driver. Why do you use it? Doesnt't the 'dummy' driver work for you? 
You can find more info about Pygame/SDL screen initialization here:
https://www.pygame.org/docs/ref/display.html

You can try to disable the double buffering using the following code:
`self.util.PYGAME_SCREEN = pygame.display.set_mode((screen_w, screen_h))`
at this line: https://github.com/project-owner/PeppyMeter/blob/1f1a6e93762cc0edd2805a8af2ad409beae3a06e/peppymeter.py#L138
That should be done for DSI and HDMI displays.

Best regards

**Comment by ocean1598** [comment]
Hi, the 'dummy' doesn't work at all. Also from what I read, 'dummy' is a loopback without the actual output. Nonetheless removing `pygame.DOUBLEBUF` did the trick. Thanks! 

The all large meters work nicely for me.

**Comment by project-owner** [comment]
Hi,

It's recommended to use the meter size which is the same as your screen resolution. Otherwise you can see different sort of issues in UI.

If large size works for you can we close the issue?

Best regards
