### ISSUE TITLE
Way to exit from PeppyMeter

### ISSUE THREAD

**Issue by phts** [project-owner/PeppyMeter#9]
I would like to programmatically exit PeppyMeter screensaver by for example triggering touch event on blank area, just to avoid making any actions which disturb playback. Or any other way to exit screensaver?

Any thoughts?

**Comment by project-owner** [comment]
There are two properties in the configuration file which have been created for this purpose:
https://github.com/project-owner/PeppyMeter/blob/c9056bd7e798e0d07bc77587c25f75dda0c80018/config.txt#L7
https://github.com/project-owner/PeppyMeter/blob/c9056bd7e798e0d07bc77587c25f75dda0c80018/config.txt#L8
I think that's what yo need.

**Comment by phts** [comment]
@project-owner Actually not exactly. 

Those configs expect touch event. So I have to simulate touch event on screen, to exit.

So my question was how actually simulate it, any ideas? Maybe you did something similar while testing the app.

Or maybe any other workarounds to force exit?

**Comment by project-owner** [comment]
What should be the action which triggers the exit? If it's programmatic action then you can use these functions:
https://github.com/project-owner/PeppyMeter/blob/c9056bd7e798e0d07bc77587c25f75dda0c80018/peppymeter.py#L228
https://github.com/project-owner/PeppyMeter/blob/c9056bd7e798e0d07bc77587c25f75dda0c80018/peppymeter.py#L251

**Comment by phts** [comment]
Is it possible to access them from outside process?

**Comment by project-owner** [comment]
No way. You need the access to the code which starts the PeppyMeter.
I've never tried that from outside of the process but you can try to simulate  a keyboard Down/Up events by creating a separate Pygame program which will post two event - Key Down and Key Up. Something like this:
https://github.com/project-owner/Peppy/blob/98faba2e1b88b3fcdb4083a600cc17dc52ff1efb/event/dispatcher.py#L313

Another way is just to find the PeppyMeter process ID in the OS and kill that process.

**Comment by phts** [comment]
thanks for the tips!

**Comment by phts** [comment]
Last question - how to find PeppyMeter process ID ? What name does it have?

**Comment by phts** [comment]
FYI managed to achieve by 

```
kill `ps ax | grep 'python3 volumio_peppymeter.py' | grep -v grep | awk '{print $1}'`
```
